//
//  Language.swift
//  Natural Language Processing
//
//  Created by Noah Wilder on 2019-03-14.
//  Copyright © 2019 Noah Wilder. All rights reserved.
//

import Foundation
import NaturalLanguage

public enum Language: String, CaseIterable {
    case afrikaans = "af"
    case afrikaansNamibia = "af_NA"
    case afrikaansSouthAfrica = "af_ZA"
    case aghem = "agq"
    case aghemCameroon = "agq_CM"
    case akan = "ak"
    case akanGhana = "ak_GH"
    case amharic = "am"
    case amharicEthiopia = "am_ET"
    case arabic = "ar"
    case arabicWorld = "ar_001"
    case arabicUnitedArabEmirates = "ar_AE"
    case arabicBahrain = "ar_BH"
    case arabicDjibouti = "ar_DJ"
    case arabicAlgeria = "ar_DZ"
    case arabicEgypt = "ar_EG"
    case arabicWesternSahara = "ar_EH"
    case arabicEritrea = "ar_ER"
    case arabicIsrael = "ar_IL"
    case arabicIraq = "ar_IQ"
    case arabicJordan = "ar_JO"
    case arabicComoros = "ar_KM"
    case arabicKuwait = "ar_KW"
    case arabicLebanon = "ar_LB"
    case arabicLibya = "ar_LY"
    case arabicMorocco = "ar_MA"
    case arabicMauritania = "ar_MR"
    case arabicOman = "ar_OM"
    case arabicPalestinianTerritories = "ar_PS"
    case arabicQatar = "ar_QA"
    case arabicSaudiArabia = "ar_SA"
    case arabicSudan = "ar_SD"
    case arabicSomalia = "ar_SO"
    case arabicSouthSudan = "ar_SS"
    case arabicSyria = "ar_SY"
    case arabicChad = "ar_TD"
    case arabicTunisia = "ar_TN"
    case arabicYemen = "ar_YE"
    case assamese = "as"
    case assameseIndia = "as_IN"
    case asu = "asa"
    case asuTanzania = "asa_TZ"
    case asturian = "ast"
    case asturianSpain = "ast_ES"
    case azerbaijani = "az"
    case azerbaijaniCyrillic = "az_Cyrl"
    case azerbaijaniCyrillicAzerbaijan = "az_Cyrl_AZ"
    case azerbaijaniLatin = "az_Latn"
    case azerbaijaniLatinAzerbaijan = "az_Latn_AZ"
    case basaa = "bas"
    case basaaCameroon = "bas_CM"
    case belarusian = "be"
    case belarusianBelarus = "be_BY"
    case bemba = "bem"
    case bembaZambia = "bem_ZM"
    case bena = "bez"
    case benaTanzania = "bez_TZ"
    case bulgarian = "bg"
    case bulgarianBulgaria = "bg_BG"
    case bambara = "bm"
    case bambaraMali = "bm_ML"
    case bengali = "bn"
    case bengaliBangladesh = "bn_BD"
    case bengaliIndia = "bn_IN"
    case tibetan = "bo"
    case tibetanChina = "bo_CN"
    case tibetanIndia = "bo_IN"
    case breton = "br"
    case bretonFrance = "br_FR"
    case bodo = "brx"
    case bodoIndia = "brx_IN"
    case bosnian = "bs"
    case bosnianCyrillic = "bs_Cyrl"
    case bosnianCyrillicBosniaHerzegovina = "bs_Cyrl_BA"
    case bosnianLatin = "bs_Latn"
    case bosnianLatinBosniaHerzegovina = "bs_Latn_BA"
    case catalan = "ca"
    case catalanAndorra = "ca_AD"
    case catalanSpain = "ca_ES"
    case catalanFrance = "ca_FR"
    case catalanItaly = "ca_IT"
    case chakma = "ccp"
    case chakmaBangladesh = "ccp_BD"
    case chakmaIndia = "ccp_IN"
    case chechen = "ce"
    case chechenRussia = "ce_RU"
    case chiga = "cgg"
    case chigaUganda = "cgg_UG"
    case cherokee = "chr"
    case cherokeeUnitedStates = "chr_US"
    case centralKurdish = "ckb"
    case centralKurdishIraq = "ckb_IQ"
    case centralKurdishIran = "ckb_IR"
    case czech = "cs"
    case czechCzechia = "cs_CZ"
    case welsh = "cy"
    case welshUnitedKingdom = "cy_GB"
    case danish = "da"
    case danishDenmark = "da_DK"
    case danishGreenland = "da_GL"
    case taita = "dav"
    case taitaKenya = "dav_KE"
    case german = "de"
    case germanAustria = "de_AT"
    case germanBelgium = "de_BE"
    case germanSwitzerland = "de_CH"
    case germanGermany = "de_DE"
    case germanItaly = "de_IT"
    case germanLiechtenstein = "de_LI"
    case germanLuxembourg = "de_LU"
    case zarma = "dje"
    case zarmaNiger = "dje_NE"
    case lowerSorbian = "dsb"
    case lowerSorbianGermany = "dsb_DE"
    case duala = "dua"
    case dualaCameroon = "dua_CM"
    case jolaFonyi = "dyo"
    case jolaFonyiSenegal = "dyo_SN"
    case dzongkha = "dz"
    case dzongkhaBhutan = "dz_BT"
    case embu = "ebu"
    case embuKenya = "ebu_KE"
    case ewe = "ee"
    case eweGhana = "ee_GH"
    case eweTogo = "ee_TG"
    case greek = "el"
    case greekCyprus = "el_CY"
    case greekGreece = "el_GR"
    case english = "en"
    case englishWorld = "en_001"
    case englishEurope = "en_150"
    case englishAndorra = "en_AD"
    case englishAntiguaBarbuda = "en_AG"
    case englishAnguilla = "en_AI"
    case englishAlbania = "en_AL"
    case englishArgentina = "en_AR"
    case englishAmericanSamoa = "en_AS"
    case englishAustria = "en_AT"
    case englishAustralia = "en_AU"
    case englishBosniaHerzegovina = "en_BA"
    case englishBarbados = "en_BB"
    case englishBangladesh = "en_BD"
    case englishBelgium = "en_BE"
    case englishBulgaria = "en_BG"
    case englishBurundi = "en_BI"
    case englishBermuda = "en_BM"
    case englishBrazil = "en_BR"
    case englishBahamas = "en_BS"
    case englishBotswana = "en_BW"
    case englishBelize = "en_BZ"
    case englishCanada = "en_CA"
    case englishCocosKeelingIslands = "en_CC"
    case englishSwitzerland = "en_CH"
    case englishCookIslands = "en_CK"
    case englishCameroon = "en_CM"
    case englishChina = "en_CN"
    case englishChristmasIsland = "en_CX"
    case englishCyprus = "en_CY"
    case englishCzechia = "en_CZ"
    case englishGermany = "en_DE"
    case englishDiegoGarcia = "en_DG"
    case englishDenmark = "en_DK"
    case englishDominica = "en_DM"
    case englishEstonia = "en_EE"
    case englishEritrea = "en_ER"
    case englishSpain = "en_ES"
    case englishFinland = "en_FI"
    case englishFiji = "en_FJ"
    case englishFalklandIslands = "en_FK"
    case englishMicronesia = "en_FM"
    case englishFrance = "en_FR"
    case englishUnitedKingdom = "en_GB"
    case englishGrenada = "en_GD"
    case englishGuernsey = "en_GG"
    case englishGhana = "en_GH"
    case englishGibraltar = "en_GI"
    case englishGambia = "en_GM"
    case englishGreece = "en_GR"
    case englishGuam = "en_GU"
    case englishGuyana = "en_GY"
    case englishHongKongChina = "en_HK"
    case englishCroatia = "en_HR"
    case englishHungary = "en_HU"
    case englishIndonesia = "en_ID"
    case englishIreland = "en_IE"
    case englishIsrael = "en_IL"
    case englishIsleOfMan = "en_IM"
    case englishIndia = "en_IN"
    case englishBritishIndianOceanTerritory = "en_IO"
    case englishIceland = "en_IS"
    case englishItaly = "en_IT"
    case englishJersey = "en_JE"
    case englishJamaica = "en_JM"
    case englishJapan = "en_JP"
    case englishKenya = "en_KE"
    case englishKiribati = "en_KI"
    case englishStKittsNevis = "en_KN"
    case englishSouthKorea = "en_KR"
    case englishCaymanIslands = "en_KY"
    case englishStLucia = "en_LC"
    case englishLiberia = "en_LR"
    case englishLesotho = "en_LS"
    case englishLithuania = "en_LT"
    case englishLuxembourg = "en_LU"
    case englishLatvia = "en_LV"
    case englishMontenegro = "en_ME"
    case englishMadagascar = "en_MG"
    case englishMarshallIslands = "en_MH"
    case englishMacauChina = "en_MO"
    case englishNorthernMarianaIslands = "en_MP"
    case englishMontserrat = "en_MS"
    case englishMalta = "en_MT"
    case englishMauritius = "en_MU"
    case englishMaldives = "en_MV"
    case englishMalawi = "en_MW"
    case englishMalaysia = "en_MY"
    case englishNamibia = "en_NA"
    case englishNorfolkIsland = "en_NF"
    case englishNigeria = "en_NG"
    case englishNetherlands = "en_NL"
    case englishNorway = "en_NO"
    case englishNauru = "en_NR"
    case englishNiue = "en_NU"
    case englishNewZealand = "en_NZ"
    case englishPapuaNewGuinea = "en_PG"
    case englishPhilippines = "en_PH"
    case englishPakistan = "en_PK"
    case englishPoland = "en_PL"
    case englishPitcairnIslands = "en_PN"
    case englishPuertoRico = "en_PR"
    case englishPortugal = "en_PT"
    case englishPalau = "en_PW"
    case englishRomania = "en_RO"
    case englishRussia = "en_RU"
    case englishRwanda = "en_RW"
    case englishSaudiArabia = "en_SA"
    case englishSolomonIslands = "en_SB"
    case englishSeychelles = "en_SC"
    case englishSudan = "en_SD"
    case englishSweden = "en_SE"
    case englishSingapore = "en_SG"
    case englishStHelena = "en_SH"
    case englishSlovenia = "en_SI"
    case englishSlovakia = "en_SK"
    case englishSierraLeone = "en_SL"
    case englishSouthSudan = "en_SS"
    case englishSintMaarten = "en_SX"
    case englishSwaziland = "en_SZ"
    case englishTurksCaicosIslands = "en_TC"
    case englishThailand = "en_TH"
    case englishTokelau = "en_TK"
    case englishTonga = "en_TO"
    case englishTurkey = "en_TR"
    case englishTrinidadTobago = "en_TT"
    case englishTuvalu = "en_TV"
    case englishTaiwan = "en_TW"
    case englishTanzania = "en_TZ"
    case englishUganda = "en_UG"
    case englishUSOutlyingIslands = "en_UM"
    case englishUnitedStates = "en_US"
    case englishUnitedStatesComputer = "en_US_POSIX"
    case englishStVincentGrenadines = "en_VC"
    case englishBritishVirginIslands = "en_VG"
    case englishUSVirginIslands = "en_VI"
    case englishVanuatu = "en_VU"
    case englishSamoa = "en_WS"
    case englishSouthAfrica = "en_ZA"
    case englishZambia = "en_ZM"
    case englishZimbabwe = "en_ZW"
    case esperanto = "eo"
    case spanish = "es"
    case spanishLatinAmerica = "es_419"
    case spanishAntiguaBarbuda = "es_AG"
    case spanishAnguilla = "es_AI"
    case spanishArgentina = "es_AR"
    case spanishAruba = "es_AW"
    case spanishBarbados = "es_BB"
    case spanishStBarthélemy = "es_BL"
    case spanishBermuda = "es_BM"
    case spanishBolivia = "es_BO"
    case spanishCaribbeanNetherlands = "es_BQ"
    case spanishBrazil = "es_BR"
    case spanishBahamas = "es_BS"
    case spanishBelize = "es_BZ"
    case spanishCanada = "es_CA"
    case spanishChile = "es_CL"
    case spanishColombia = "es_CO"
    case spanishCostaRica = "es_CR"
    case spanishCuba = "es_CU"
    case spanishCuraçao = "es_CW"
    case spanishDominica = "es_DM"
    case spanishDominicanRepublic = "es_DO"
    case spanishCeutaMelilla = "es_EA"
    case spanishEcuador = "es_EC"
    case spanishSpain = "es_ES"
    case spanishFalklandIslands = "es_FK"
    case spanishGrenada = "es_GD"
    case spanishFrenchGuiana = "es_GF"
    case spanishGreenland = "es_GL"
    case spanishGuadeloupe = "es_GP"
    case spanishEquatorialGuinea = "es_GQ"
    case spanishGuatemala = "es_GT"
    case spanishGuyana = "es_GY"
    case spanishHonduras = "es_HN"
    case spanishHaiti = "es_HT"
    case spanishCanaryIslands = "es_IC"
    case spanishStKittsNevis = "es_KN"
    case spanishCaymanIslands = "es_KY"
    case spanishStLucia = "es_LC"
    case spanishStMartin = "es_MF"
    case spanishMartinique = "es_MQ"
    case spanishMontserrat = "es_MS"
    case spanishMexico = "es_MX"
    case spanishNicaragua = "es_NI"
    case spanishPanama = "es_PA"
    case spanishPeru = "es_PE"
    case spanishPhilippines = "es_PH"
    case spanishStPierreMiquelon = "es_PM"
    case spanishPuertoRico = "es_PR"
    case spanishParaguay = "es_PY"
    case spanishSuriname = "es_SR"
    case spanishElSalvador = "es_SV"
    case spanishSintMaarten = "es_SX"
    case spanishTurksCaicosIslands = "es_TC"
    case spanishTrinidadTobago = "es_TT"
    case spanishUnitedStates = "es_US"
    case spanishUruguay = "es_UY"
    case spanishStVincentGrenadines = "es_VC"
    case spanishVenezuela = "es_VE"
    case spanishBritishVirginIslands = "es_VG"
    case spanishUSVirginIslands = "es_VI"
    case estonian = "et"
    case estonianEstonia = "et_EE"
    case basque = "eu"
    case basqueSpain = "eu_ES"
    case ewondo = "ewo"
    case ewondoCameroon = "ewo_CM"
    case persian = "fa"
    case persianAfghanistan = "fa_AF"
    case persianIran = "fa_IR"
    case fulah = "ff"
    case fulahCameroon = "ff_CM"
    case fulahGuinea = "ff_GN"
    case fulahMauritania = "ff_MR"
    case fulahSenegal = "ff_SN"
    case finnish = "fi"
    case finnishFinland = "fi_FI"
    case filipino = "fil"
    case filipinoPhilippines = "fil_PH"
    case faroese = "fo"
    case faroeseDenmark = "fo_DK"
    case faroeseFaroeIslands = "fo_FO"
    case french = "fr"
    case frenchBelgium = "fr_BE"
    case frenchBurkinaFaso = "fr_BF"
    case frenchBurundi = "fr_BI"
    case frenchBenin = "fr_BJ"
    case frenchStBarthélemy = "fr_BL"
    case frenchCanada = "fr_CA"
    case frenchCongoKinshasa = "fr_CD"
    case frenchCentralAfricanRepublic = "fr_CF"
    case frenchCongoBrazzaville = "fr_CG"
    case frenchSwitzerland = "fr_CH"
    case frenchCoteDivoire = "fr_CI"
    case frenchCameroon = "fr_CM"
    case frenchDjibouti = "fr_DJ"
    case frenchAlgeria = "fr_DZ"
    case frenchFrance = "fr_FR"
    case frenchGabon = "fr_GA"
    case frenchFrenchGuiana = "fr_GF"
    case frenchGuinea = "fr_GN"
    case frenchGuadeloupe = "fr_GP"
    case frenchEquatorialGuinea = "fr_GQ"
    case frenchHaiti = "fr_HT"
    case frenchComoros = "fr_KM"
    case frenchLuxembourg = "fr_LU"
    case frenchMorocco = "fr_MA"
    case frenchMonaco = "fr_MC"
    case frenchStMartin = "fr_MF"
    case frenchMadagascar = "fr_MG"
    case frenchMali = "fr_ML"
    case frenchMartinique = "fr_MQ"
    case frenchMauritania = "fr_MR"
    case frenchMauritius = "fr_MU"
    case frenchNewCaledonia = "fr_NC"
    case frenchNiger = "fr_NE"
    case frenchFrenchPolynesia = "fr_PF"
    case frenchStPierreMiquelon = "fr_PM"
    case frenchRéunion = "fr_RE"
    case frenchRwanda = "fr_RW"
    case frenchSeychelles = "fr_SC"
    case frenchSenegal = "fr_SN"
    case frenchSyria = "fr_SY"
    case frenchChad = "fr_TD"
    case frenchTogo = "fr_TG"
    case frenchTunisia = "fr_TN"
    case frenchVanuatu = "fr_VU"
    case frenchWallisFutuna = "fr_WF"
    case frenchMayotte = "fr_YT"
    case friulian = "fur"
    case friulianItaly = "fur_IT"
    case westernFrisian = "fy"
    case westernFrisianNetherlands = "fy_NL"
    case irish = "ga"
    case irishIreland = "ga_IE"
    case scottishGaelic = "gd"
    case scottishGaelicUnitedKingdom = "gd_GB"
    case galician = "gl"
    case galicianSpain = "gl_ES"
    case swissGerman = "gsw"
    case swissGermanSwitzerland = "gsw_CH"
    case swissGermanFrance = "gsw_FR"
    case swissGermanLiechtenstein = "gsw_LI"
    case gujarati = "gu"
    case gujaratiIndia = "gu_IN"
    case gusii = "guz"
    case gusiiKenya = "guz_KE"
    case manx = "gv"
    case manxIsleOfMan = "gv_IM"
    case hausa = "ha"
    case hausaGhana = "ha_GH"
    case hausaNiger = "ha_NE"
    case hausaNigeria = "ha_NG"
    case hawaiian = "haw"
    case hawaiianUnitedStates = "haw_US"
    case hebrew = "he"
    case hebrewIsrael = "he_IL"
    case hindi = "hi"
    case hindiIndia = "hi_IN"
    case croatian = "hr"
    case croatianBosniaHerzegovina = "hr_BA"
    case croatianCroatia = "hr_HR"
    case upperSorbian = "hsb"
    case upperSorbianGermany = "hsb_DE"
    case hungarian = "hu"
    case hungarianHungary = "hu_HU"
    case armenian = "hy"
    case armenianArmenia = "hy_AM"
    case indonesian = "id"
    case indonesianIndonesia = "id_ID"
    case igbo = "ig"
    case igboNigeria = "ig_NG"
    case sichuanYi = "ii"
    case sichuanYiChina = "ii_CN"
    case icelandic = "is"
    case icelandicIceland = "is_IS"
    case italian = "it"
    case italianSwitzerland = "it_CH"
    case italianItaly = "it_IT"
    case italianSanMarino = "it_SM"
    case italianVaticanCity = "it_VA"
    case inuktitut = "iu"
    case inuktitutCanada = "iu_CA"
    case japanese = "ja"
    case japaneseJapan = "ja_JP"
    case ngomba = "jgo"
    case ngombaCameroon = "jgo_CM"
    case machame = "jmc"
    case machameTanzania = "jmc_TZ"
    case georgian = "ka"
    case georgianGeorgia = "ka_GE"
    case kabyle = "kab"
    case kabyleAlgeria = "kab_DZ"
    case kamba = "kam"
    case kambaKenya = "kam_KE"
    case makonde = "kde"
    case makondeTanzania = "kde_TZ"
    case kabuverdianu = "kea"
    case kabuverdianuCapeVerde = "kea_CV"
    case koyraChiini = "khq"
    case koyraChiiniMali = "khq_ML"
    case kikuyu = "ki"
    case kikuyuKenya = "ki_KE"
    case kazakh = "kk"
    case kazakhKazakhstan = "kk_KZ"
    case kako = "kkj"
    case kakoCameroon = "kkj_CM"
    case kalaallisut = "kl"
    case kalaallisutGreenland = "kl_GL"
    case kalenjin = "kln"
    case kalenjinKenya = "kln_KE"
    case khmer = "km"
    case khmerCambodia = "km_KH"
    case kannada = "kn"
    case kannadaIndia = "kn_IN"
    case korean = "ko"
    case koreanNorthKorea = "ko_KP"
    case koreanSouthKorea = "ko_KR"
    case konkani = "kok"
    case konkaniIndia = "kok_IN"
    case kashmiri = "ks"
    case kashmiriIndia = "ks_IN"
    case shambala = "ksb"
    case shambalaTanzania = "ksb_TZ"
    case bafia = "ksf"
    case bafiaCameroon = "ksf_CM"
    case colognian = "ksh"
    case colognianGermany = "ksh_DE"
    case cornish = "kw"
    case cornishUnitedKingdom = "kw_GB"
    case kyrgyz = "ky"
    case kyrgyzKyrgyzstan = "ky_KG"
    case langi = "lag"
    case langiTanzania = "lag_TZ"
    case luxembourgish = "lb"
    case luxembourgishLuxembourg = "lb_LU"
    case ganda = "lg"
    case gandaUganda = "lg_UG"
    case lakota = "lkt"
    case lakotaUnitedStates = "lkt_US"
    case lingala = "ln"
    case lingalaAngola = "ln_AO"
    case lingalaCongoKinshasa = "ln_CD"
    case lingalaCentralAfricanRepublic = "ln_CF"
    case lingalaCongoBrazzaville = "ln_CG"
    case lao = "lo"
    case laoLaos = "lo_LA"
    case northernLuri = "lrc"
    case northernLuriIraq = "lrc_IQ"
    case northernLuriIran = "lrc_IR"
    case lithuanian = "lt"
    case lithuanianLithuania = "lt_LT"
    case lubaKatanga = "lu"
    case lubaKatangaCongoKinshasa = "lu_CD"
    case luo = "luo"
    case luoKenya = "luo_KE"
    case luyia = "luy"
    case luyiaKenya = "luy_KE"
    case latvian = "lv"
    case latvianLatvia = "lv_LV"
    case masai = "mas"
    case masaiKenya = "mas_KE"
    case masaiTanzania = "mas_TZ"
    case meru = "mer"
    case meruKenya = "mer_KE"
    case mauritian = "mfe"
    case mauritianMauritius = "mfe_MU"
    case malagasy = "mg"
    case malagasyMadagascar = "mg_MG"
    case makhuwaMeetto = "mgh"
    case makhuwaMeettoMozambique = "mgh_MZ"
    case metaʼ = "mgo"
    case metaʼCameroon = "mgo_CM"
    case macedonian = "mk"
    case macedonianMacedonia = "mk_MK"
    case malayalam = "ml"
    case malayalamIndia = "ml_IN"
    case mongolian = "mn"
    case mongolianMongolia = "mn_MN"
    case marathi = "mr"
    case marathiIndia = "mr_IN"
    case malay = "ms"
    case malayArabic = "ms_Arab"
    case malayArabicBrunei = "ms_Arab_BN"
    case malayArabicMalaysia = "ms_Arab_MY"
    case malayBrunei = "ms_BN"
    case malayMalaysia = "ms_MY"
    case malaySingapore = "ms_SG"
    case maltese = "mt"
    case malteseMalta = "mt_MT"
    case mundang = "mua"
    case mundangCameroon = "mua_CM"
    case burmese = "my"
    case burmeseMyanmarBurma = "my_MM"
    case mazanderani = "mzn"
    case mazanderaniIran = "mzn_IR"
    case nama = "naq"
    case namaNamibia = "naq_NA"
    case norwegianBokmål = "nb"
    case norwegianBokmålNorway = "nb_NO"
    case norwegianBokmålSvalbardJanMayen = "nb_SJ"
    case northNdebele = "nd"
    case northNdebeleZimbabwe = "nd_ZW"
    case lowGerman = "nds"
    case lowGermanGermany = "nds_DE"
    case lowGermanNetherlands = "nds_NL"
    case nepali = "ne"
    case nepaliIndia = "ne_IN"
    case nepaliNepal = "ne_NP"
    case dutch = "nl"
    case dutchAruba = "nl_AW"
    case dutchBelgium = "nl_BE"
    case dutchCaribbeanNetherlands = "nl_BQ"
    case dutchCuraçao = "nl_CW"
    case dutchNetherlands = "nl_NL"
    case dutchSuriname = "nl_SR"
    case dutchSintMaarten = "nl_SX"
    case kwasio = "nmg"
    case kwasioCameroon = "nmg_CM"
    case norwegianNynorsk = "nn"
    case norwegianNynorskNorway = "nn_NO"
    case ngiemboon = "nnh"
    case ngiemboonCameroon = "nnh_CM"
    case nuer = "nus"
    case nuerSouthSudan = "nus_SS"
    case nyankole = "nyn"
    case nyankoleUganda = "nyn_UG"
    case oromo = "om"
    case oromoEthiopia = "om_ET"
    case oromoKenya = "om_KE"
    case odia = "or"
    case odiaIndia = "or_IN"
    case ossetic = "os"
    case osseticGeorgia = "os_GE"
    case osseticRussia = "os_RU"
    case punjabi = "pa"
    case punjabiArabic = "pa_Arab"
    case punjabiArabicPakistan = "pa_Arab_PK"
    case punjabiGurmukhi = "pa_Guru"
    case punjabiGurmukhiIndia = "pa_Guru_IN"
    case polish = "pl"
    case polishPoland = "pl_PL"
    case pashto = "ps"
    case pashtoAfghanistan = "ps_AF"
    case portuguese = "pt"
    case portugueseAngola = "pt_AO"
    case portugueseBrazil = "pt_BR"
    case portugueseSwitzerland = "pt_CH"
    case portugueseCapeVerde = "pt_CV"
    case portugueseFrance = "pt_FR"
    case portugueseEquatorialGuinea = "pt_GQ"
    case portugueseGuineaBissau = "pt_GW"
    case portugueseLuxembourg = "pt_LU"
    case portugueseMacauChina = "pt_MO"
    case portugueseMozambique = "pt_MZ"
    case portuguesePortugal = "pt_PT"
    case portugueseSãoToméPríncipe = "pt_ST"
    case portugueseTimorLeste = "pt_TL"
    case quechua = "qu"
    case quechuaBolivia = "qu_BO"
    case quechuaEcuador = "qu_EC"
    case quechuaPeru = "qu_PE"
    case romansh = "rm"
    case romanshSwitzerland = "rm_CH"
    case rundi = "rn"
    case rundiBurundi = "rn_BI"
    case romanian = "ro"
    case romanianMoldova = "ro_MD"
    case romanianRomania = "ro_RO"
    case rombo = "rof"
    case romboTanzania = "rof_TZ"
    case russian = "ru"
    case russianBelarus = "ru_BY"
    case russianKyrgyzstan = "ru_KG"
    case russianKazakhstan = "ru_KZ"
    case russianMoldova = "ru_MD"
    case russianRussia = "ru_RU"
    case russianUkraine = "ru_UA"
    case kinyarwanda = "rw"
    case kinyarwandaRwanda = "rw_RW"
    case rwa = "rwk"
    case rwaTanzania = "rwk_TZ"
    case sakha = "sah"
    case sakhaRussia = "sah_RU"
    case samburu = "saq"
    case samburuKenya = "saq_KE"
    case sangu = "sbp"
    case sanguTanzania = "sbp_TZ"
    case northernSami = "se"
    case northernSamiFinland = "se_FI"
    case northernSamiNorway = "se_NO"
    case northernSamiSweden = "se_SE"
    case sena = "seh"
    case senaMozambique = "seh_MZ"
    case koyraboroSenni = "ses"
    case koyraboroSenniMali = "ses_ML"
    case sango = "sg"
    case sangoCentralAfricanRepublic = "sg_CF"
    case tachelhit = "shi"
    case tachelhitLatin = "shi_Latn"
    case tachelhitLatinMorocco = "shi_Latn_MA"
    case tachelhitTifinagh = "shi_Tfng"
    case tachelhitTifinaghMorocco = "shi_Tfng_MA"
    case sinhala = "si"
    case sinhalaSriLanka = "si_LK"
    case slovak = "sk"
    case slovakSlovakia = "sk_SK"
    case slovenian = "sl"
    case slovenianSlovenia = "sl_SI"
    case inariSami = "smn"
    case inariSamiFinland = "smn_FI"
    case shona = "sn"
    case shonaZimbabwe = "sn_ZW"
    case somali = "so"
    case somaliDjibouti = "so_DJ"
    case somaliEthiopia = "so_ET"
    case somaliKenya = "so_KE"
    case somaliSomalia = "so_SO"
    case albanian = "sq"
    case albanianAlbania = "sq_AL"
    case albanianMacedonia = "sq_MK"
    case albanianKosovo = "sq_XK"
    case serbian = "sr"
    case serbianCyrillic = "sr_Cyrl"
    case serbianCyrillicBosniaHerzegovina = "sr_Cyrl_BA"
    case serbianCyrillicMontenegro = "sr_Cyrl_ME"
    case serbianCyrillicSerbia = "sr_Cyrl_RS"
    case serbianCyrillicKosovo = "sr_Cyrl_XK"
    case serbianLatin = "sr_Latn"
    case serbianLatinBosniaHerzegovina = "sr_Latn_BA"
    case serbianLatinMontenegro = "sr_Latn_ME"
    case serbianLatinSerbia = "sr_Latn_RS"
    case serbianLatinKosovo = "sr_Latn_XK"
    case swedish = "sv"
    case swedishÅlandIslands = "sv_AX"
    case swedishFinland = "sv_FI"
    case swedishSweden = "sv_SE"
    case swahili = "sw"
    case swahiliCongoKinshasa = "sw_CD"
    case swahiliKenya = "sw_KE"
    case swahiliTanzania = "sw_TZ"
    case swahiliUganda = "sw_UG"
    case tamil = "ta"
    case tamilIndia = "ta_IN"
    case tamilSriLanka = "ta_LK"
    case tamilMalaysia = "ta_MY"
    case tamilSingapore = "ta_SG"
    case telugu = "te"
    case teluguIndia = "te_IN"
    case teso = "teo"
    case tesoKenya = "teo_KE"
    case tesoUganda = "teo_UG"
    case tajik = "tg"
    case tajikTajikistan = "tg_TJ"
    case thai = "th"
    case thaiThailand = "th_TH"
    case tigrinya = "ti"
    case tigrinyaEritrea = "ti_ER"
    case tigrinyaEthiopia = "ti_ET"
    case turkmen = "tk"
    case turkmenTurkmenistan = "tk_TM"
    case tongan = "to"
    case tonganTonga = "to_TO"
    case turkish = "tr"
    case turkishCyprus = "tr_CY"
    case turkishTurkey = "tr_TR"
    case tatar = "tt"
    case tatarRussia = "tt_RU"
    case tasawaq = "twq"
    case tasawaqNiger = "twq_NE"
    case centralAtlasTamazight = "tzm"
    case centralAtlasTamazightMorocco = "tzm_MA"
    case uyghur = "ug"
    case uyghurChina = "ug_CN"
    case ukrainian = "uk"
    case ukrainianUkraine = "uk_UA"
    case urdu = "ur"
    case urduIndia = "ur_IN"
    case urduPakistan = "ur_PK"
    case uzbek = "uz"
    case uzbekArabic = "uz_Arab"
    case uzbekArabicAfghanistan = "uz_Arab_AF"
    case uzbekCyrillic = "uz_Cyrl"
    case uzbekCyrillicUzbekistan = "uz_Cyrl_UZ"
    case uzbekLatin = "uz_Latn"
    case uzbekLatinUzbekistan = "uz_Latn_UZ"
    case vai = "vai"
    case vaiLatin = "vai_Latn"
    case vaiLatinLiberia = "vai_Latn_LR"
    case vaiVai = "vai_Vaii"
    case vaiVaiLiberia = "vai_Vaii_LR"
    case vietnamese = "vi"
    case vietnameseVietnam = "vi_VN"
    case vunjo = "vun"
    case vunjoTanzania = "vun_TZ"
    case walser = "wae"
    case walserSwitzerland = "wae_CH"
    case wolof = "wo"
    case wolofSenegal = "wo_SN"
    case soga = "xog"
    case sogaUganda = "xog_UG"
    case yangben = "yav"
    case yangbenCameroon = "yav_CM"
    case yiddish = "yi"
    case yiddishWorld = "yi_001"
    case yoruba = "yo"
    case yorubaBenin = "yo_BJ"
    case yorubaNigeria = "yo_NG"
    case cantonese = "yue"
    case cantoneseSimplifiedHan = "yue_Hans"
    case cantoneseSimplifiedHanChina = "yue_Hans_CN"
    case cantoneseTraditionalHan = "yue_Hant"
    case cantoneseTraditionalHanHongKongChina = "yue_Hant_HK"
    case standardMoroccanTamazight = "zgh"
    case standardMoroccanTamazightMorocco = "zgh_MA"
    case chinese = "zh"
    case chineseSimplifiedHan = "zh_Hans"
    case chineseSimplifiedHanChina = "zh_Hans_CN"
    case chineseSimplifiedHanHongKongChina = "zh_Hans_HK"
    case chineseSimplifiedHanMacauChina = "zh_Hans_MO"
    case chineseSimplifiedHanSingapore = "zh_Hans_SG"
    case chineseTraditionalHan = "zh_Hant"
    case chineseTraditionalHanHongKongChina = "zh_Hant_HK"
    case chineseTraditionalHanMacauChina = "zh_Hant_MO"
    case chineseTraditionalHanTaiwan = "zh_Hant_TW"
    case zulu = "zu"
    case zuluSouthAfrica = "zu_ZA"
}

//┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┃ MARK: - Initializers
public extension Language {
    
    /// Creates a language with the specified identifier.
    init? <T: StringProtocol>(identifier: T) {
        let identifier = Locale(identifier: String(identifier)).identifier
        self.init(rawValue: identifier)
    }
    
    /// Creates a language of the specified locale.
    init? (locale: Locale) {
        let identifier = locale.identifier
        self.init(rawValue: identifier)
    }
    
    
    /// Creates a language that corresponds to the dominant language in the specified string.
    init? <T: StringProtocol>(of string: T) {

        guard let dominantLanguage = NLLanguageRecognizer.dominantLanguage(for: String(string)) else {
            return nil
        }
        self.init(identifier: dominantLanguage.rawValue)
    }
    
    /// Creates a language of the `NLLanguage`.
    init (nlLanguage: NLLanguage) {
        let identifier = nlLanguage.rawValue
        self.init(rawValue: identifier)!
    }
}


//┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┃ MARK: - Computed Properties
public extension Language {
    
    /// A language representing the user's region settings at the time the property is read.
    static var current: Language {
        return Language(locale: Locale.current)!
    }
    
    /// The locale of the language.
    var locale: Locale {
        return Locale(identifier: identifier)
    }
    
    /// The language converted to an instance of NLLanguage.
    var nlLanguage: NLLanguage {
        return NLLanguage(identifier)
    }
    
    /// The identifier of the language.
    var identifier: String {
        return rawValue
    }
    
    /// The name of the language in language's locale.
    var localizedName: String {
        return locale.fullLocalizedString(forIdentifier: identifier) ?? "Unknown"
    }
    
    /// The full name of the language in the current locale.
    var name: String {
        return Locale.current.fullLocalizedString(forIdentifier: identifier)!
    }
    
    /// The line direction of the language.
    var lineDirection: Locale.LanguageDirection {
        return Locale.lineDirection(forLanguage: locale.languageCode!)
    }
    
    /// The character direction of the language.
    var characterDirection: Locale.LanguageDirection {
        return Locale.characterDirection(forLanguage: locale.languageCode!)
    }
    
    /// The calendar for the language, or the Gregorian calendar as a fallback.
    var calendar: Calendar {
        return locale.calendar
    }
    
    /// The region code of the language, or `nil` if it has none.
    var regionCode: String? {
        return locale.regionCode
    }
    
    /// The language code of the language, or `nil` if has none.
    var languageCode: String? {
        return locale.languageCode
    }
    
    /// The script code of the language, or `nil` if has none.
    var scriptCode: String? {
        return locale.scriptCode
    }
    
    /// The variant code for the language, or `nil` if it has none.
    var variantCode: String? {
        return locale.variantCode
    }
    
    /// The exemplar character set for the language, or `nil` if has none.
    var exemplarCharacterSet: CharacterSet? {
        return locale.exemplarCharacterSet
    }
    
    /// The collation identifier for the language, or `nil` if it has none.
    var collationIdentifier: String? {
        return locale.collationIdentifier
    }
    
    /// The collator identifier of the language.
    var collatorIdentifier: String? {
        return locale.collatorIdentifier
    }
    
    /// A Boolean that is true if the language uses the metric system.
    var usesMetricSystem: Bool {
        return locale.usesMetricSystem
    }
    
    /// The decimal separator of the language.
    var decimalSeparator: String? {
        return locale.decimalSeparator
    }
    
    /// The grouping separator of the language.
    var groupingSeparator: String? {
        return locale.groupingSeparator
    }
    
    /// The currency code of the language.
    var currencyCode: String? {
        return locale.currencyCode
    }
    
    /// The currency symbol of the language.
    var currencySymbol: String? {
        return locale.currencySymbol
    }
    
    /// The quotation begin delimiter of the language.
    var quotationBeginDelimiter: String? {
        return locale.quotationBeginDelimiter
    }
    
    /// The quotation end delimiter of the language.
    var quotationEndDelimiter: String? {
        return locale.quotationEndDelimiter
    }
    
    /// The alternate quotation begin delimiter of the language.
    var alternateQuotationBeginDelimiter: String? {
        return locale.alternateQuotationBeginDelimiter
    }
    
    /// The alternate quotation end delimiter of the language.
    var alternateQuotationEndDelimiter: String? {
        return locale.alternateQuotationEndDelimiter
    }
    
    
}



//┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//┃ MARK: - CustomStringConvertible Conformance
extension Language: CustomStringConvertible {
    
    /// A textual description of the language.
    public var description: String {
        return name
    }
    
}
